name: Test Self-Hosted Runner
on: [workflow_dispatch]  # 允许手动触发

jobs:
  test:
    runs-on: self-hosted  # 关键：指定使用你的 Runner
    steps:
      - run: echo "Hello from Self-Hosted Runner!"
      - run: uname -a  # 打印系统信息（验证 Runner 环境）